smvcfei/Models/CustomIdentityUser.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;

namespace smvcfei.Models
{
    public class CustomIdentityUser: IdentityUser
    {
        [PersonalData]
        [Display(Name = "Nombre")]
        public string Nombrecompleto { get; set; }
    }
}

smvcfei/Models/ErrorViewModel.cs
namespace smvcfei.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

smvcfei/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;
namespace smvcfei.Models
{
    public class LoginViewModel
    {
        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        [EmailAddress(ErrorMessage = "El campo {0} no es correo válido")]
        [Display(Name = "Correo electrónico")]

        public string Correo { get; set; }

        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        [DataType(DataType.Password)]
        [Display(Name = "Contraseña")]

        public string Password { get; set; }
    }
}

smvcfei/Models/UsuarioViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace smvcfei.Models
{
    public class UsuarioViewModel
    {
        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        [EmailAddress(ErrorMessage = "El campo {0} no es correo válido")]
        [Display(Name = "Correo electrónico")]

        public string Correo { get; set; }

        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        [Display(Name = "Nombre completo")]

        public string Nombre { get; set; }

        [Required(ErrorMessage = "El campo {0} es obligatorio.")]

        public string Rol { get; set; }

        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        [DataType(DataType.Password)]
        [Display(Name = "Contraseña")]

        public string Password { get; set; }

        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        [Compare(otherProperty: "Password", ErrorMessage = "Las contraseñas no coinciden.")]
        [DataType(DataType.Password)]
        [Display(Name = "Confirme su contraseña")]

        public string ConfirmPassword { get; set; }
    }
}

smvcfei/Controllers/CuentasController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using smvcfei.Data;
using smvcfei.Models;

namespace smvcfei.Controllers
{
    [Authorize]

    public class CuentasController : Controller
    {
        private readonly IdentityContext _context;
        private readonly UserManager<CustomIdentityUser> _userManager;
        private readonly SignInManager<CustomIdentityUser> _signInManager;

        public CuentasController(IdentityContext context, UserManager<CustomIdentityUser> userManager, SignInManager<CustomIdentityUser> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public async Task<IActionResult> LoginAsync(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    bool signInResult = false;
                    var result = await _signInManager.PasswordSignInAsync(model.Correo, model.Password, isPersistent: false, lockoutOnFailure: false);
                    signInResult = result.Succeeded;

                    if (signInResult)
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        ModelState.AddModelError("Correo", "Credenciales no válidas. Inténtelo nuevamente");
                    }
                }
                catch(Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Registro(bool creado = false)
        {
            ViewData["creado"] = creado;
            ViewData["RolesSelect"] = new SelectList(await _context.Roles.OrderBy(r => r.Name).AsNoTracking().ToListAsync(), "Name", "Name", null);
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> RegistroAsync(UsuarioViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var usuario = await _userManager.FindByEmailAsync(model.Correo);
                    if(usuario == null){
                        var usuarioToCreate = new CustomIdentityUser
                        {
                            UserName = model.Correo,
                            Email = model.Correo,
                            NormalizedEmail = model.Correo.ToUpper(),
                            Nombrecompleto = model.Nombre,
                            NormalizedUserName = model.Correo.ToUpper(),
                        };
                        IdentityResult result = await _userManager.CreateAsync(usuarioToCreate, model.Password);
                        if (result.Succeeded)
                        {
                            await _userManager.AddToRoleAsync(usuarioToCreate, model.Rol);
                            return RedirectToAction(nameof(RegistroAsync), new { creado = true });
                        }

                        List<IdentityError> errorList = result.Errors.ToList();
                        var errors = string.Join(" ", errorList.Select(e => e.Description));
                        ModelState.AddModelError("Password", errors);
                    }
                    else
                    {
                        ModelState.AddModelError("Correo", $"El usuario {usuario.UserName} ya existe");
                    }
                }
                catch (DbUpdateException ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }
            ViewData["creado"] = false;
            return View();
        }

        public async Task<IActionResult> PerfilAsync()
        {
            var identityUser = await _userManager.FindByEmailAsync(User.Identity.Name);
            var roles = _userManager.GetRolesAsync(identityUser).Result;
            var rol = string.Join(",", roles);

            UsuarioViewModel usuario = new()
            {
                Nombre = identityUser.Nombrecompleto,
                Correo = identityUser.Email,
                Rol = rol
            };
        return View(usuario);
        }

        public async Task<IActionResult> LogoutAsync(string returUrl = null)
        {
            await _signInManager.SignOutAsync();

            if(returUrl != null)
            {
                return LocalRedirect(returUrl);
            }
            else 
            {
                return RedirectToAction("Login");
            }
        }

        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

smvcfei/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using smvcfei.Models;
using System.Diagnostics;

namespace smvcfei.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]

        public IActionResult Privacy()
        {
            return View();
        }

        [Authorize(Roles = "Administrador")]

        public IActionResult SoloParaAdministradores()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

smvcfei/Views/Cuenta/Login.cshtml
@model LoginViewModel
@{
    ViewData["Title"] = "Inicio de Sesión";
}

<h1 class="h3 text-center text-success">Desarrollo de Sistemas Web</h1>
<h2 class="h5 text-center text-muted">Licenciatura en ingenieria de software</h2>

<form asp-action="Login">
    <div class="card mx-auto mt-3" style="max-width: 500px;">
        <div class="card-body">
            <h5 class="card-card-title text-center">@ViewData["Title"]</h5>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mb-3">
                <label asp-for="Correo" class="form-label"></label>
                <input asp-for="Correo" class="form-control" />
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Password" class="form-label"></label>
                <input asp-for="Password" class="form-control">
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
        </div>
        <div class="card-footer text-center">
            <button type="submit" class="btn btn-primary">Iniciar sesión</button>
        </div>
    </div>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

smvcfei/Views/Cuenta/Perfil.cshtml
@model UsuarioViewModel
@{
    ViewData["Title"] = "Perfil de usuario";
}

<h2 class="text-center mb-4">@ViewData["Title"]</h2>

<div class="card text-dark bg-light mt-3">
    <div class="card-header">
        @Model.Nombre
    </div>
    <div class="card-body">
        <div class="form-text mb-2">
            <div class="text-dark">@Html.DisplayNameFor(model => model.Correo)</div>
            @Model.Correo
        </div>
        <div class="form-text mb-2">
            <div class="text-dark">@Html.DisplayNameFor(model => model.Rol)</div>
            @Model.Rol
        </div>
    </div>
</div>

smvcfei/Views/Cuenta/Registro.cshtml
@model UsuarioViewModel
@{
    ViewData["Title"] = "Crear nuevo usuario";
}

<h2 class="text-center mb-4">@ViewData["Title"]</h2>
@if ((bool)ViewData["creado"])
{
    <div class="alert alert-success alert-dismissible fade show mx-auto" style="max-width: 600px" role="alert">
        El usuario se ha creado con éxito
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<form asp-action="Registro">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="card mt-3 mx-auto" style="max-width: 600px">
        <div class="card-header">
            Datos de usuario
        </div>
        <div class="card-body">
            <div class="mb-3">
                <label asp-for="Correo" class="form-label"></label>
                <input asp-for="Correo" class="form-control">
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Nombre" class="form-label"></label>
                <input asp-for="Nombre" class="form-control">
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="mb-3 obligatorio">
                <label asp-for="Rol" class="form-label"></label>
                <select asp-for="Rol" asp-items='(SelectList)ViewData["RolesSelect"]' class="form-control">
                    <option value="">Seleccione un valor para este campo</option>
                </select>
                <span asp-validation-for="Rol" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Password" class="form-label"></label>
                <input asp-for="Password" class="form-control">
                <div class="small text-secondary">Se recomienda ingrese una contraseña fuerte</div>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="ConfirmPassword" class="form-label"></label>
                <input asp-for="ConfirmPassword" class="form-control">
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
        </div>
        <div class="card-footer text-center">
            <button type="submit" class="btn btn-primary">Crear usuario</button>
        </div>
    </div>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial"/>
}

smvcfei/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página de inicio";
}

<div class="text-center">
    <h1 class="h3 text-center text-success">Desarrollo de Sistemas Web</h1>
    <h2 class="h5 text-center text-muted">Licenciatura en ingeniería de software</h2>
    <p class="display-5 mt-5">Bienvenidos</p>
</div>

smvcfei/Views/Home/SoloParaAdministradores.cshtml
@{
    ViewData["Title"] = "Página protegida para administradores";
}
<h1>@ViewData["Title"]</h1>
<p>Esta página requiere autenticación del usuario <stromg> con rol Administrador</stromg> para poder visualizarse</p>

smvcfei/Views/Shared/AccessDenied.cshtml
@{
    ViewData["Title"] = "Acceso denegado";
}

<div class="container my-2">
    <h1 class="text-danger">@ViewData["Title"]</h1>
    <p class="text-muted">El usuario actual no tiene acceso a este apartado</p>
</div>

smvcfei/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - smvcfei</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/smvcfei.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">smvcfei</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Protegido</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="SoloParaAdministradores">Administradores</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - smvcfei - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

smvcfei/Views/Shared_LoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<CustomIdentityUser> SignInManager
@inject UserManager<CustomIdentityUser> UserManager

<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Cuentas" asp-action="Perfil">Hola @(User.Identity?.Name)!</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Cuentas" asp-action="Logout" asp-route-returnUrl="@Url.Action("Index","Home")">Salir</a>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Cuentas" asp-action="Registro">Registrarse</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Cuentas" asp-action="Login">Iniciar sesión</a>
        </li>
    }
</ul>